Update gae_buildout.rst
The last commit exposes that the virtual environment doesn't have buildout installed:

$ ../bin/python2.7 bootstrap.py
Traceback (most recent call last):
  File "bootstrap.py", line 108, in <module>
    pkg_resources.Requirement.parse('distribute')).location
AttributeError: 'NoneType' object has no attribute 'location'